//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcessPoint
    {
        public int ID { get; set; }
        public int ComputerID { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public int GIndex { get; set; }
        public int Gtype { get; set; }
        public Nullable<int> InKeyID { get; set; }
        public Nullable<int> InDuration { get; set; }
        public Nullable<int> InCommand { get; set; }
        public Nullable<int> OutKeyID { get; set; }
        public Nullable<int> OutDuration { get; set; }
        public Nullable<int> OutCommand { get; set; }
        public Nullable<int> InKeyID2 { get; set; }
        public Nullable<int> InDuration2 { get; set; }
        public Nullable<int> InCommand2 { get; set; }
        public Nullable<int> OutKeyID2 { get; set; }
        public Nullable<int> OutDuration2 { get; set; }
        public Nullable<int> OutCommand2 { get; set; }
        public Nullable<int> Config { get; set; }
        public Nullable<int> IndexZone1 { get; set; }
        public Nullable<int> IndexZone2 { get; set; }
        public Nullable<int> IndexZone3 { get; set; }
        public Nullable<int> IndexZone4 { get; set; }
        public Nullable<int> WorkTimeZone1 { get; set; }
        public Nullable<int> WorkTimeZone2 { get; set; }
        public Nullable<int> WorkTimeZone3 { get; set; }
        public Nullable<int> WorkTimeZone4 { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> WeightTerminalID { get; set; }
    }
}
