//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Orion2019Entities : DbContext
    {
        public Orion2019Entities()
            : base("name=Orion2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PDivision> PDivision { get; set; }
        public virtual DbSet<pList> pList { get; set; }
        public virtual DbSet<pLogData> pLogData { get; set; }
        public virtual DbSet<PCompany> PCompany { get; set; }
    }
}
