//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCompany
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Id_Number_Company { get; set; }
        public string GUID_1C { get; set; }
        public Nullable<int> IsGuest { get; set; }
    }
}
