//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDivision
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Shedule { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> PCompany_ID { get; set; }
        public string ID_Number_Division { get; set; }
        public Nullable<int> ID_Owner_Division { get; set; }
        public Nullable<int> Patterns_ID { get; set; }
        public string GUID_1C { get; set; }
    }
}
