//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class pList
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public int Status { get; set; }
        public string WorkPhone { get; set; }
        public string HomePhone { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> Company { get; set; }
        public Nullable<int> Section { get; set; }
        public Nullable<int> Post { get; set; }
        public Nullable<int> Schedule { get; set; }
        public string Avto { get; set; }
        public Nullable<int> Spack { get; set; }
        public Nullable<int> Config { get; set; }
        public string TabNumber { get; set; }
        public Nullable<int> GrStatus { get; set; }
        public Nullable<System.DateTime> ChangeTime { get; set; }
        public Nullable<int> IndexForContactId { get; set; }
        public Nullable<int> StatusRecord { get; set; }
        public Nullable<int> Patterns_ID { get; set; }
        public string ID_Number_List { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> delta_weight { get; set; }
        public Nullable<int> AutoID { get; set; }
        public string GUID_1C { get; set; }
        public Nullable<int> status_list { get; set; }
        public string EmailList { get; set; }
        public Nullable<int> fielddelete { get; set; }
        public Nullable<int> BlackList { get; set; }
        public string INN { get; set; }
        public string ReasonToBlackList { get; set; }
        public Nullable<int> TypeDocum { get; set; }
        public Nullable<int> SexGuest { get; set; }
        public string DokumSeries { get; set; }
        public string DokumNumber { get; set; }
        public Nullable<System.DateTime> DateDocument { get; set; }
        public string KodPodr { get; set; }
        public string Kem { get; set; }
        public Nullable<System.DateTime> DateDocumentEnd { get; set; }
        public string birthplace { get; set; }
        public Nullable<System.DateTime> DateTimeInArchive { get; set; }
        public string FireToList { get; set; }
        public Nullable<int> IDSCAN { get; set; }
        public Nullable<int> IDGROUPEXIT { get; set; }
    }
}
